### ISSUE TITLE
Fork of Antimicro/antimicro

### ISSUE THREAD

**Issue by frealgagu** [AmenStop/antimicro#3]
Is this a fork of https://github.com/AntiMicro/antimicro
?

**Comment by AdamKane41** [comment]
;-D yeah...  side project of mine...
Try it, it works great!

**Comment by trymeouteh** [comment]
Are you gonna keep developing this and also release it for other Linux distros and for Windows?

**Comment by frealgagu** [comment]
It looks like this not being maintained anymore.
